# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '8081:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html:rw'
        networks:
            - sail
        depends_on:
            mysql:
              condition: service_healthy
            redis:
              condition: service_healthy
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-4306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - sail
        healthcheck:
          test: [ "CMD", "mysqladmin" ,"ping"]
          timeout: 20s
          retries: 10
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-7379}:6379'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
networks:
    sail:
        driver: bridge
